name: Pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [
          "3.11",
          "3.12-dev",
        ]
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test-pypi-example-samuelvitor
        run: |
          python -m pip install .[ci]
          pip freeze

      - name: Run mypy
        run: |
          mypy --check-untyped-defs --python-version 3.11 --ignore-missing-imports ./src

      - name: Run ruff
        run: ruff check .

      - name: Run pytest
        run: python -m pytest --tb=short --disable-warnings